[project]
name = "data-science-course"
version = "0.1.0"
requires-python = ">=3.12,<3.13"
dependencies = [
  "jupyter-book~=2.1.6",
  "jupyterlab~=4.6.3",
  "jupyterlab-myst~=2.7.0",
  "matplotlib~=3.11.2",
  "numpy~=2.5.3",
  "pandas~=3.0.5",
  "seaborn~=0.13.2",
  "scikit-learn~=1.9.1",
  "kagglehub~=1.0.2",
  "ipywidgets~=8.1.9",
  "statsmodels~=0.15.0",
  "torch~=2.14.0",
  "torchvision~=0.29.0",
  "pyLHD @ git+https://github.com/toledo60/pyLHD.git@68d4d5b52ffe2513e1bfe01680bb12d376a02fa8",
]

[tool.uv]
package = false
